### ISSUE TITLE
input text format?

### ISSUE THREAD

**Issue by tc64** [iwnsew/ngweight#1]
Hi, thanks a lot for putting the code from your paper online!

I'd like to know the proper input text format - how should documents be separated? Any formatting restrictions?

Thanks.

**Comment by iwnsew** [comment]
Thank you for getting interested in this tool.

Each input document has a header starting by ASCII code "0x02" and ending by "0x03".
This header acts as a separator for documents.

Any texts between "0x02" and "0x03" are auxiliary information and ignored when processing texts.
In sample_text file, Wikipedia page id was added between "0x02" and "0x03".

Other remarkable formatting restriction is that each word should be delimited by space characters.
Symbols (e.g., ' and -) can also be a delimiter in this implementation.

**Comment by tc64** [comment]
Thanks!
