### ISSUE TITLE
doc frequency for wiki corpus results?

### ISSUE THREAD

**Issue by tc64** [iwnsew/ngweight#2]
For the wikipedia corpus output you provide (link in README), when calculating weight1 and weight2, what is the correct document frequency to use?

**Comment by iwnsew** [comment]
Output file consists of six columns following the output format in README.

Specifically, weight1 uses the total number of Wikipedia pages (4,379,810) and sdf (fifth column),
and weight2 uses them and df (fourth column).

**Comment by tc64** [comment]
thanks, that answers my question.
